Wakeup animation made
viilis/unwritten pull request #35
Opened 2024-11-22 10:57 UTC by Juhoton

Wakeup animation done, still need to add script to disable input, just in case. 
Still needs to be tested with other scenes.

2024-11-22 11:02 UTC, viilis requested changes

2024-11-22 11:02 UTC, viilis commented on debug.log
delete this

2024-11-22 11:02 UTC, viilis commented on .vsconfig
don't push these

2024-11-22 13:11 UTC, Juhoton commented on ProjectSettings/EditorBuildSettings.asset
These should be on master?

2024-11-22 13:12 UTC, Juhoton commented on Assets/Prefabs/Movable_Player.prefab
Not sure about the huge deletion of stuff

2024-11-22 13:44 UTC, Juhoton commented on Assets/Prefabs/Movable_Player.prefab
It actually moves them around, so I'm not sure if that is problematic or not.
Lines 3-94 are moved to 231-304

2024-11-26 15:01 UTC, Juhoton commented on debug.log
Deleted

2024-11-26 15:01 UTC, Juhoton commented on .vsconfig
Removed

2024-11-28 14:29 UTC, viilis approved these changes

2024-11-28 14:39 UTC, merged